LIKECLOVA/LUCKIT

- src/components/header/header.jsx
- src/components/header/headerstyle.jsx
- src/components/navbar/navbar.jsx
- src/components/navbar/navbarstyle.jsx
- src/pages/home/Home2.jsx
- src/pages/home/home.jsx
- src/pages/home/homestyle.jsx
- src/pages/pages.jsx
- src/pages/profile/profile.jsx
- src/pages/profile/profilestyle.jsx
- src/pages/search/search.jsx
-
- header, navbar, homepage 기본 레이아웃 마크업 했습니다.
close : #
> Feat: header, navbar, homepage 마크업 완료

- src/components/join/joinProfile.jsx
- src/pages/chat/chatPage.jsx
- src/pages/home/home.jsx
- src/pages/pages.jsx
- src/pages/profile/myProfile.jsx
- src/pages/profile/yourProfile.jsx
- src/pages/search/search.jsx
- src/pages/sns/snsUpload.jsx
-
-파일명 자체는 다 소문자. 다만 띄어쓰기가 있는경우 카멜케이스.
스타일 컴포넌트 파일은 띄어쓰기 상관없이 다 소문자처리
close : #
> Rename: 파일 및  경로명 수정

- src/styles/global/Allwrap.jsx
> Style: Allwrap 높이 넓이 값 수정

- src/components/join/joinProfile.jsx
- src/components/join/joinprofilestyle.jsx
> Feat: 회원가입 프로필 설정 페이지 마크업 완료

- src/components/navbar/navBar.jsx
- src/pages/home/Home2.jsx
- src/pages/home/home.jsx
- src/pages/home/homestyle.jsx
-
- 홈페이지 디자인 변경으로 기본 마크업 수정했습니다.
close : #
> Refactor: 홈페이지 기본 마크업 수정

- package-lock.json
- package.json
- src/components/mainpost/mainMarketPost.jsx
- src/components/mainpost/mainSnsPost.jsx
- src/components/mainpost/mainpoststyle.jsx
- src/pages/home/home.jsx
- src/pages/sns/snsPage.jsx
- src/pages/sns/snsUpload.jsx
- src/pages/sns/snsstyle.jsx
- sns피드 마크업을 완료하고 mainsnspost 컴포넌트를 작성하였다.
-
close : #
> Feat/sns피드마크업 완료

- src/components/follow/follow.jsx
- src/components/follow/followstyle.jsx
- src/pages/follow/followstyle.jsx
- src/pages/follow/myFollow.jsx
- src/pages/follow/yourFollow.jsx
-
- 내 프로필 페이지. 상대방 프로필 페이지에 있는 팔로워 팔로잉을 누르면 이동하는 페이지 마크업 완료했습니다. 유저 정보가 뜨는 팔로우 컴포넌트도 마크업 완료했습니다.
close : #
> Feat: myFollow페이지 yourFollow페이지 follow 컴포넌트 마크업 완료

- src/components/comment/comment-box/commentBox.jsx
- src/components/comment/comment-list/commentList.jsx
- src/components/comment/comment-reply/commentReply.jsx
- src/components/comment/commentstyle.jsx
- src/components/mainpost/mainSnsPost.jsx
- src/components/mainpost/mainpoststyle.jsx
- src/components/sns-post/snsPost.jsx
- src/components/sns-post/snspoststyle.jsx
- src/pages/pages.jsx
- src/pages/sns/snsPage.jsx
- snspost페이지 마크업 완료 및 comment컴포넌트마크업 완료
-
close : #
> Feat: snspost페이지 마크업

- src/pages/pages.jsx
- src/pages/profile/editProfile.jsx
- src/pages/profile/editprofilestyle.jsx
- src/pages/profile/myprofilestyle.jsx
> Feat: 프로필 수정 페이지 마크업 완료

- src/components/modal/modal.jsx
- src/components/modal/modalstyle.jsx
-
- 모달 컴포넌트 기본 마크업 했습니다.
close : #
> Feat: 모달컴포넌트기본마크업

- src/components/navbar/navBar.jsx
- src/components/navbar/navbarstyle.jsx
- 네비바 각 항목 hover, 클릭 시 아이콘과 색상 변경이 됩니다.
-
close : #
> Refactor: 네비바 마크업 수정

- src/components/button/iconBtnstyle.jsx
- src/components/mainpost/mainpoststyle.jsx
- snspoststyle 필요없는 부분 수정 및 iconBtn부분에 주석 추가
-
close : #
> Feat: snspost스타일 수정

- src/components/navbar/navBar.jsx
- 아이콘의 위치를 변경하여 네비바의 이미지경로를 수정해주었다.
-
close : #
> Feat: 네비바 이미지경로 수정

- src/components/carousel/carousel.jsx
- src/components/carousel/carouselstyle.jsx
-
- 임시로 지정한 이미지 경로가 유효하지 않아 수정했습니다.
- 이미지는 추후 정해진 이미지로 변경 예정입니다.
- 이전 슬라이드, 다음 슬라이드 버튼을 투명 처리했습니다.
close : #
> Fix: 캐러셀 컴포넌트 이미지 url 수정

- src/components/button/iconBtn.jsx
- src/components/button/iconBtnstyle.jsx
- src/components/mainpost/mainSnsPost.jsx
- src/components/mainpost/mainpoststyle.jsx
- src/components/uploadbtn/marketUpload.jsx
- src/pages/sns/snsUpload.jsx
> Feat: 아이콘버튼컴포넌트추가

- .eslintrc.json
- src/components/button/iconBtn.jsx
- src/components/join/joinProfile.jsx
- src/components/join/joinprofilestyle.jsx
-
-회원가입 페이지에서 이메일, 비밀번호 데이터를 받아서 회원가입 post하는 것만 남겨두고 다 했습니다.
close : #42
> Feat: 회원가입 프로필 설정 구현완료

- src/components/button/button.jsx
- src/components/button/buttonstyle.jsx
- src/components/header/header.jsx
- src/components/header/headerstyle.jsx
- src/pages/chat/chatPage.jsx
- src/pages/chat/chatRoom.jsx
- src/pages/follow/myFollow.jsx
- src/pages/follow/yourFollow.jsx
- src/pages/home/Home2.jsx
- src/pages/home/home.jsx
- src/pages/profile/editProfile.jsx
- src/pages/profile/myProfile.jsx
- src/pages/profile/yourProfile.jsx
- src/pages/search/search.jsx
- src/pages/search/searchstyle.jsx
- src/pages/sns/snsPage.jsx
- 각 아이콘 클릭 시 해당 헤더가 적용됩니다.
- 우선 한 파일에 헤더 컴포넌트 만들었습니다. 
- 버튼 컴포넌트에 Upload 버튼 추가했습니다.
- 이전에 만든 헤더가 적용되어 있는 파일은 모두 해당하는 헤더 컴포넌트로 수정했습니다.
close : #
> Feat: 헤더 컴포넌트 구현

- src/components/button/iconBtn.jsx
- src/components/button/iconBtnstyle.jsx
- src/components/join/joinProfile.jsx
- src/components/join/joinprofilestyle.jsx
-
- 아이콘 이미지 버튼에 이미지 태그를 지우고 배경url이미지로 수정하였습니다.
사유: 이미지 태그를 쓰면 프로필 설정 페이지 이미지 태그과 css속성 겹침발생
close : #
> Fix: 회원가입 프로필 설정 페이지 이미지 버튼 수정

- src/components/button/iconBtn.jsx
- src/components/button/iconBtnstyle.jsx
- src/components/follow/follow.jsx
- src/components/follow/followstyle.jsx
- src/components/header/header.jsx
- src/components/header/headerstyle.jsx
- src/components/profile-box/profileBox.jsx
- src/components/profile-box/profilestyle.jsx
- src/pages/follow/myFollow.jsx
- src/pages/profile/myProfile.jsx
- src/pages/profile/myprofilestyle.jsx
> Feat: myfollow 페이지 기능구현 완료

- src/components/market-preview-post/marketPreviewPost.jsx
- src/components/market-preview-post/marketpreviewboxstyle.jsx
- src/components/profile-box/profileBox.jsx
- src/components/profile-box/profilestyle.jsx
- src/pages/profile/myProfile.jsx
- src/pages/profile/myprofilestyle.jsx
- 각 명세서에 맞게 데이터가 잘 렌더링 됨
- 일반 게시글 리스트형, 앨범형 아이콘 클릭 시 색상 변화(이미지 변경)는 아직 구현하지 않았습니다.
close : #
> Feat/마이 프로필 페이지 기능 구현

- src/components/mainpost/mainSnsPost.jsx
- src/components/mainpost/mainpoststyle.jsx
- src/components/sns-post/snsPost.jsx
- src/pages/pages.jsx
- src/pages/sns/snsPage.jsx
- mainSnsPost의 코멘트나 이미지 또는 댓글 창을 눌렀을 때 해당 게시글 상세페이지로 이동
- mainSnsPost의 유저프로필 이미지나 닉네임 또는 핸들을 눌렀을 때 해당 유저페이지로 이동
-
close : #65
> Feat: 게시글 상세페이지 조회 기능구현

- src/components/join/join.jsx
- src/components/join/joinProfile.jsx
- src/components/join/joinstyle.jsx
- email input 값이 바뀔 때마다 유효성 검사 진행, '올바른 이메일 형식이 아닙니다.' 메세지 출력
- password input 값이 변할 때마다 유효성 검사 진행, '비밀번호는 6자 이상이어야 합니다.' 메세지 출력
-
close : #73
> Feat: 회원가입 기능 구현

- src/assets/icon/addBtn.svg
- src/components/button/button.jsx
- src/components/button/iconBtn.jsx
- src/components/button/iconBtnstyle.jsx
- src/pages/sns/snsPage.jsx
- src/pages/sns/snsstyle.jsx
- 피드에 게시글 업로드 버튼 추가
- 팔로잉한 사람이 없을 경우 뜨는 페이지 지정
-
close : #77
> Feat: sns피드페이지 기능추가

- .eslintrc.json
- src/components/button/button.jsx
- src/components/button/buttonstyle.jsx
- src/components/join/join.jsx
- src/components/join/joinProfile.jsx
- src/pages/search/searchstyle.jsx
유효성 검사 완료.
회원가입시 로그인페이지로 이동.
-
-
close : #
> Feat: 회원가입 기능구현 완성

- src/components/follow/follow.jsx
- src/components/follow/followstyle.jsx
- src/components/profile-box/profileBox.jsx
- src/pages/follow/followstyle.jsx
- src/pages/follow/myFollow.jsx
- src/pages/follow/yourFollow.jsx
- src/pages/profile/editProfile.jsx
- src/pages/profile/myProfile.jsx
> Feat: 상대방 팔로우 페이지 기능구현 완료

- src/components/mainpost/mainSnsPost.jsx
- src/components/mainpost/mainpoststyle.jsx
- 게시글에 이미지가 2장이상이면 캐러셀 구현
-
close : #90
> Feat: 게시글조회 추가기능 구현

- src/Route.js
- src/pages/pages.jsx
- src/pages/start/start.jsx
-
- 맨 처음에만 스플래시 페이지가 나타나고 그 이후엔 로그인 스크린을 띄우는 걸로 처리했습니다. 
- 다른 페이지 접근시 바로 로그인 페이지로 이동
close : #
> Feat: 로그인 인증에 따른 페이지 라우팅 기능 구현 완료

- src/pages/profile/editProfile.jsx
> Feat: 프로필 수정 페이지에 저장 버튼 클릭시 페이지이동 기능 추가

- src/pages/pages.jsx
> Fix: 상품 수정 주소 변경

- src/pages/profile/myProfile.jsx
- sns 피드 페이지 게시글과 동일한 컴포넌트로 수정
close : #106
> Refactor: 프로필 페이지 sns 게시글 컴포넌트 수정

- src/components/button/iconBtn.jsx
- src/components/mainpost/mainSnsPost.jsx
- src/components/modal/modal.jsx
- src/pages/sns/snsPage.jsx
- src/pages/sns/snsUpload.jsx
> Feat: Sns게시글 삭제 기능구현

- src/components/button/button.jsx
- src/components/header/header.jsx
- src/components/sns-post/snsPost.jsx
- src/pages/sns/snsUpload.jsx
> Design: 게시글 업로드페이지 디자인

- src/components/button/iconBtn.jsx
- src/components/comment/commentBox.jsx
- src/components/comment/commentlist/commentList.jsx
- src/components/modal/modal.jsx
> Feat: 댓글삭제 기능구현

- src/pages/home/MarketFeedHome.jsx
- src/pages/home/home.jsx
- 팔로잉 한 사용자 있을 경우 사용자들의 마켓 게시글이 렌더링 됨
close : #
> Feat/홈페이지 axios 이용해 마켓 게시글 렌더링

- src/components/market-post/marketUpdate/marketUpdate.jsx
- src/components/market-preview-post/marketPreviewPost.jsx
- src/components/modal/modal.jsx
- 삭제 버튼을 누르면 상품이 삭제됨
close : #124
> Feat: 마켓 상품 삭제 기능 구현

- src/pages/home/MarketFeedHome.jsx
- src/styles/global/globalStyle.jsx
- 클로바 버튼을 클릭하면 gif가 들어간 선택할 수 있는 모달창이 열림
- 럭킷 매칭 신청을 누르면 gif가 들어간 '매칭 신청이 완료되었습니다' 모달창이 뜸
close : #126
> Design: 홈 마켓 피드 모달 수정

- src/App.js
- src/styles/global/Allwrap.jsx
> Design: Allwrap 디자인 수정

- src/pages/sns/snsUpload.jsx
> Feat: 게시글업로드 오류해결

- src/components/button/iconBtn.jsx
- src/components/mainpost/mainSnsPost.jsx
- src/components/modal/modal.jsx
- src/pages/pages.jsx
- src/pages/sns/snsModify.jsx
> Feat: 게시글수정 기능구현

- src/components/button/iconBtn.jsx
- src/components/mainpost/marketPostBox.jsx
- src/pages/home/MarketFeedHome.jsx
- src/pages/home/homestyle.jsx
- 홈페이지 마켓 게시글 컴포넌트 적용
close : #136
> Refactor: 홈페이지 마켓 게시글 컴포넌트 적용

- package-lock.json
- package.json
- src/components/market-post/marketUpdate/marketUpdate.jsx
- src/pages/market/marketPost.jsx
- src/styles/global/Allwrap.jsx
- 상품 수정 클릭 시 기존 데이터가 잘 받아와지고, 수정이 잘 됨
close : #
> Fix: 상품 수정 기능 구현 수정

- src/components/carousel/carousel.jsx
- src/pages/pages.jsx
> Fix: 캐러셀 이미지 수정

- src/components/carousel/carousel.jsx
- src/pages/pages.jsx
> Fix: 캐러셀 이미지 오류 수정

- src/pages/home/MarketFeedHome.jsx
- src/pages/home/home.jsx
- scrollTop 수치가 변할 때마다 재렌더링 되지 않고, scrollTop 수치 300을 기준으로 재렌더링 됨
close : #151
> Fix: 홈페이지 onScroll 이벤트 재렌더링 관련 코드 수정

- src/components/button/iconBtn.jsx
- src/components/button/iconBtnstyle.jsx
- src/components/header/header.jsx
> Feat: 뒤로가기 버튼 컴포넌트 구현

- src/components/follow/follow.jsx
- src/components/follow/followstyle.jsx
- src/pages/follow/myFollow.jsx
- src/pages/follow/yourFollow.jsx
- src/reducers/getFollowSlice.js
- src/store.js
> Fix: 상대방 팔로우 팔로워 페이지에서 내 프로필을 팔로우 하는 버튼이 보이는 오류 해결

- src/components/mainpost/marketpostboxstyle.jsx
- src/components/market-post/marketUpload/marketImage.jsx
- src/components/market-post/marketUpload/marketinputstyle.jsx
- 홈 피드 마켓의 모달 크기가 알맞은 크기로 보임
- 마켓 상품 수정 시 이미지가 확대되지 않고, 크기에 맞게 잘 담겨서 보임
close : #
> Fix: 홈 피드 마켓 모달 크기, 마켓 상품 수정 이미지 크기 수정

- .gitignore
- src/components/mainpost/marketPostBox.jsx
- src/components/market-preview-post/marketPreviewPost.jsx
> Fix: 에러 이미지 처리

- src/components/navbar/navbarstyle.jsx
- src/pages/chat/chatPage.jsx
- src/pages/map/map.jsx
> Feat: 채팅 페이지 & 지도 페이지 네브바 추가

- src/components/mainpost/mainpoststyle.jsx
- src/pages/profile/myprofilestyle.jsx
- sns피드페이지 게시글 조회 컴포넌트 디자인
close : #150
> Design:sns피드페이지 디자인

- src/components/follow/follow.jsx
- src/components/follow/followstyle.jsx
- src/pages/follow/followstyle.jsx
> Style: 팔로우 페이지 css 수정 완료

- src/components/header/header.jsx
- src/components/header/headerstyle.jsx
> Design: 헤더 CSS 수정

- src/pages/profile/editProfile.jsx
- src/pages/profile/editprofilestyle.jsx
> Style: 프로필 수정 페이지 css 수정 완료

- src/components/profile-box/profileBox.jsx
> Fix: profile 수정 바로 안되는 문제 해결

- src/components/button/buttonstyle.jsx
- src/components/button/iconBtnstyle.jsx
- src/components/join/joinProfile.jsx
- src/components/join/joinprofilestyle.jsx
> Style: 회원가입 프로필 설정 페이지 css 수정

- src/pages/sns/snsModify.jsx
- 게시물수정버튼 활성화 기능구현
close : #187
> Feat: 게시물수정버튼 활성화 기능구현

- src/components/button/iconBtn.jsx
- src/components/button/iconBtnstyle.jsx
- src/components/mainpost/mainpoststyle.jsx
- src/pages/sns/snsstyle.jsx
-  sns피드페이지 디자인 했습니다.
close : #190
> Design: sns피드페이지 디자인

- src/pages/sns/snsstyle.jsx
> Design: sns업로드페이지 디자인

- src/components/button/iconBtn.jsx
- src/components/button/iconBtnstyle.jsx
- src/components/comment/commentboxstyle.jsx
- src/components/comment/commentinput/commentinputstyle.jsx
- src/components/comment/commentlist/commentList.jsx
- src/components/comment/commentlist/commentliststyle.jsx
- src/components/mainpost/mainpoststyle.jsx
- src/components/sns-post-box/snsPostBox.jsx
- src/components/sns-post/snsPost.jsx
- src/components/sns-post/snspoststyle.jsx
> Feat: sns상세페이지 디자인

- src/components/modal/modal.jsx
- 상세페이지에서 게시글 삭제 시 프로필로 이동하도록 수정
close : #195
> Rename: 상세페이지 게시글삭제 시 프로필로 이동

- src/components/button/button.jsx
- src/components/button/buttonstyle.jsx
- src/components/comment/commentinput/commentInput.jsx
- src/components/comment/commentlist/commentList.jsx
- src/components/mainpost/mainSnsPost.jsx
- src/components/sns-post/snsPost.jsx
- src/pages/sns/snsModify.jsx
- src/pages/sns/snsPage.jsx
- src/pages/sns/snsUpload.jsx
- src/pages/sns/snsstyle.jsx
> refactor: sns페이지 리팩토링

- src/components/join/joinProfile.jsx
- src/components/market-preview-post/marketPreviewPost.jsx
- src/pages/home/MarketFeedHome.jsx
- src/pages/home/home.jsx
- src/pages/market/marketPost.jsx
- src/pages/pages.jsx
- src/pages/profile/myProfile.jsx
- src/reducers/getProductListSlice.js
- src/reducers/getSnsPostSlice.js
- src/store.js
- 중복된 코드 제거. 불필요한 렌더링 줄이기
close : #186
> Refactor/redux 홈페이지 중복된 axios 코드 리덕스로 수정

- src/components/mainpost/marketPostBox.jsx
- 홈 피드 모달 사진이 교체돼서 잘 보임
close : #
> Design: 홈 피드 모달 사진 및 CSS 수정

- src/components/button/iconBtn.jsx
- src/pages/home/MarketFeedHome.jsx
- src/pages/home/home.jsx
- src/pages/profile/myProfile.jsx
- src/pages/search/search.jsx
- src/pages/sns/snsPage.jsx
> Refactor: 변수명 수정

- src/components/mainpost/marketpostboxstyle.jsx
- src/pages/profile/myProfile.jsx
> Refactor: 프로필 페이지 sns 게시글 없어도 snsPostBtn 뜨도록 수정

- src/components/mainpost/mainSnsPost.jsx
- src/components/mainpost/mainpoststyle.jsx
- 링크 범위지정 및 컴포넌트 이름변경
close : #
> Fix: sns페이지 리팩토링

- package-lock.json
- package.json
- src/components/loading/loading.jsx
- src/pages/sns/snsPage.jsx
- sns피드 무한스크롤 기능구현
close : #214
> Feat: sns피드 무한스크롤 기능구현

- src/components/comment/commentlist/commentliststyle.jsx
- src/components/mainpost/mainpoststyle.jsx
- src/pages/sns/snsPage.jsx
> fix: sns피드비율조정

- src/components/button/heart/heartbtnstyle.jsx
- src/components/button/iconBtnstyle.jsx
- src/components/mainpost/mainpoststyle.jsx
- src/components/sns-post/snspoststyle.jsx
- src/pages/sns/snsstyle.jsx
- src/styles/global/globalColor.jsx
> Fix: sns페이지 css수정

- src/components/header/headerstyle.jsx
- src/components/mainpost/marketpostboxstyle.jsx
- src/components/market-preview-post/marketPreviewPost.jsx
- src/components/market-preview-post/marketpreviewpoststyle.jsx
- src/components/navbar/navbarstyle.jsx
- src/components/profile-box/profileboxstyle.jsx
- src/pages/home/homestyle.jsx
- src/pages/market/marketPost.jsx
- src/pages/market/marketpoststyle.jsx
- src/pages/profile/myprofilestyle.jsx
- src/pages/search/searchstyle.jsx
> Refactor: 전체적인 CSS 코드 수정

- package-lock.json
- package.json
- src/components/sns-post/snsPost.jsx
- src/pages/404-error/errorPage.jsx
- src/pages/chat/chatPage.jsx
- src/pages/chat/chatRoom.jsx
- src/pages/follow/myFollow.jsx
- src/pages/follow/yourFollow.jsx
- src/pages/home/defaultHome.jsx
- src/pages/home/home.jsx
- src/pages/map/map.jsx
- src/pages/market/marketPost.jsx
- src/pages/profile/editProfile.jsx
- src/pages/profile/myProfile.jsx
- src/pages/search/search.jsx
- src/pages/sns/snsModify.jsx
- src/pages/sns/snsPage.jsx
- src/pages/sns/snsUpload.jsx
> Feat: 모든 페이지 헬멧 추가

- src/components/header/header.jsx
- src/pages/chat/chatPage.jsx
- src/pages/chat/chatRoom.jsx
- src/pages/chat/chatRoomSec.jsx
- src/pages/pages.jsx
- 채팅 목록에서 쿠로미를 누르면 쿠로미 채팅방이 연결됨
close : #
> Design: 쿠로미 채팅방 연결

- src/pages/map/map.jsx
- src/pages/sns/snsPage.jsx
> Fix: key 값 id로 수정

- src/components/navbar/navBar.jsx
- src/pages/map/map.jsx
- src/pages/sns/snsPage.jsx
- src/pages/sns/snsstyle.jsx
- Navbar에 SNS 게시글이 가려지는 현상 해결
close : #
> Fix: SNS 피드 게시글 잘림 해결

- src/pages/sns/snsModify.jsx
- src/pages/sns/snsPage.jsx
- src/pages/sns/snsUpload.jsx
> Docs: SNS 철자 수정

- src/pages/chat/chatuserstyle.jsx
- src/pages/home/homestyle.jsx
- 채팅 페이지 글자가 온전히 보임
close : #234
> Design: 채팅 페이지 CSS 수정

- src/components/join/joinProfile.jsx
> Refactor: 회원가입 프로필 설정페이지 유효성 검사 문구 수정

- src/pages/sns/snsstyle.jsx
> Design: sns 페이지 CSS 수정

- src/pages/map/markPosition.jsx
> Fix: 마커 위치조정

- src/components/follow/follow.jsx
> Fix: 팔로우 컴포넌트 아이디 닉네임 위치변경

- src/App.js
- src/components/sns-post/snsPost.jsx
- src/pages/404-error/errorPage.jsx
- src/pages/chat/chatPage.jsx
- src/pages/chat/chatRoom.jsx
- src/pages/chat/chatRoomSec.jsx
- src/pages/follow/myFollow.jsx
- src/pages/follow/yourFollow.jsx
- src/pages/home/defaultHome.jsx
- src/pages/home/home.jsx
- src/pages/map/map.jsx
- src/pages/market/marketPost.jsx
- src/pages/profile/editProfile.jsx
- src/pages/profile/myProfile.jsx
- src/pages/search/search.jsx
- src/pages/sns/snsModify.jsx
- src/pages/sns/snsPage.jsx
- src/pages/sns/snsUpload.jsx
- Helmet provider를 app.js에 감싸서 각 페이지 코드에서 삭제
close : #
> Fix: Helmet 중복되는부분 삭제

- src/components/button/heartBtn/heartBtn.jsx
- src/components/comment/commentinput/commentInput.jsx
- src/components/follow/follow.jsx
- src/components/join/join.jsx
- src/components/join/joinProfile.jsx
- src/components/login/login.jsx
- src/components/market-post/marketUpdate/marketUpdate.jsx
- src/components/market-post/marketUpload/marketImage.jsx
- src/components/market-post/marketUpload/marketUpload.jsx
- src/components/market-preview-post/marketPreviewPost.jsx
- src/components/modal/modal.jsx
- src/components/profile-box/profileBox.jsx
- src/components/sns-post/snsPost.jsx
- src/pages/follow/myFollow.jsx
- src/pages/follow/yourFollow.jsx
- src/pages/home/MarketFeedHome.jsx
- src/pages/home/home.jsx
- src/pages/market/marketPost.jsx
- src/pages/profile/editProfile.jsx
- src/pages/profile/myProfile.jsx
- src/pages/search/search.jsx
- src/pages/sns/snsModify.jsx
- src/pages/sns/snsPage.jsx
- src/pages/sns/snsUpload.jsx
- src/pages/start/start.jsx
- src/reducers/getUserInfoSlice.js
> Fix: api 주소 변경
